CREATE TABLE  IF NOT EXISTS CAR 
   (	CALLNO VARCHAR(500), 
	CARNAME VARCHAR(500), 
	COMPANY VARCHAR(500), 
	CONDTN VARCHAR(500), 
	QUANTITY INT, 
	ISSUED INT, 
	 CONSTRAINT CAR_PK PRIMARY KEY (CALLNO)
   )
;
CREATE TABLE  IF NOT EXISTS CAROWNER 
   (	ID INT AUTO_INCREMENT, 
	NAME VARCHAR(500), 
	PASSWORD VARCHAR(500), 
	EMAIL VARCHAR(500), 
	MOBILE BIGINT , 
	 CONSTRAINT CAROWNER_PK PRIMARY KEY (ID)
   )
;

-- Note: ID must be generated through sequence in E_LIBRARIAN table.

CREATE TABLE  IF NOT EXISTS ISSUECAR 
   (	CALLNO VARCHAR(500) NOT NULL, 
	CUSTOMERID VARCHAR(500) NOT NULL, 
	CUSTOMERNAME VARCHAR(500), 
	CUSTOMERMOBILE INT, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(500)
   )
;
